// flow-typed signature: 712632fdab316b37f565940eec693d8c
// flow-typed version: <<STUB>>/postcss-class-prefix_v^0.3.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-class-prefix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-class-prefix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-class-prefix/index' {
  declare module.exports: $Exports<'postcss-class-prefix'>;
}
declare module 'postcss-class-prefix/index.js' {
  declare module.exports: $Exports<'postcss-class-prefix'>;
}
