// flow-typed signature: 965599d76ebe6f1e6c77493a20c0e29f
// flow-typed version: <<STUB>>/wicg-focus-ring_v^3.0.2/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wicg-focus-ring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wicg-focus-ring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wicg-focus-ring/dist/focus-ring' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/rollup.config' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/src/focus-ring' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/button' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/contenteditable-textbox' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/contenteditable-true' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/contenteditable' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/helpers' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-checkbox' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-color' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-date' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-file' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-number' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-radio-group' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-radio' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-range' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-submit' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-text' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/input-time' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/select-multiple' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/select-size' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/select' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/tabindex-negative-one' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/tabindex-one' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/tabindex-zero' {
  declare module.exports: any;
}

declare module 'wicg-focus-ring/test/specs/textarea' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wicg-focus-ring/dist/focus-ring.js' {
  declare module.exports: $Exports<'wicg-focus-ring/dist/focus-ring'>;
}
declare module 'wicg-focus-ring/rollup.config.js' {
  declare module.exports: $Exports<'wicg-focus-ring/rollup.config'>;
}
declare module 'wicg-focus-ring/src/focus-ring.js' {
  declare module.exports: $Exports<'wicg-focus-ring/src/focus-ring'>;
}
declare module 'wicg-focus-ring/test/index' {
  declare module.exports: $Exports<'wicg-focus-ring/test'>;
}
declare module 'wicg-focus-ring/test/index.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test'>;
}
declare module 'wicg-focus-ring/test/specs/button.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/button'>;
}
declare module 'wicg-focus-ring/test/specs/contenteditable-textbox.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/contenteditable-textbox'>;
}
declare module 'wicg-focus-ring/test/specs/contenteditable-true.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/contenteditable-true'>;
}
declare module 'wicg-focus-ring/test/specs/contenteditable.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/contenteditable'>;
}
declare module 'wicg-focus-ring/test/specs/helpers/index' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/helpers'>;
}
declare module 'wicg-focus-ring/test/specs/helpers/index.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/helpers'>;
}
declare module 'wicg-focus-ring/test/specs/input-checkbox.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-checkbox'>;
}
declare module 'wicg-focus-ring/test/specs/input-color.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-color'>;
}
declare module 'wicg-focus-ring/test/specs/input-date.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-date'>;
}
declare module 'wicg-focus-ring/test/specs/input-file.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-file'>;
}
declare module 'wicg-focus-ring/test/specs/input-number.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-number'>;
}
declare module 'wicg-focus-ring/test/specs/input-radio-group.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-radio-group'>;
}
declare module 'wicg-focus-ring/test/specs/input-radio.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-radio'>;
}
declare module 'wicg-focus-ring/test/specs/input-range.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-range'>;
}
declare module 'wicg-focus-ring/test/specs/input-submit.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-submit'>;
}
declare module 'wicg-focus-ring/test/specs/input-text.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-text'>;
}
declare module 'wicg-focus-ring/test/specs/input-time.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/input-time'>;
}
declare module 'wicg-focus-ring/test/specs/select-multiple.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/select-multiple'>;
}
declare module 'wicg-focus-ring/test/specs/select-size.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/select-size'>;
}
declare module 'wicg-focus-ring/test/specs/select.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/select'>;
}
declare module 'wicg-focus-ring/test/specs/tabindex-negative-one.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/tabindex-negative-one'>;
}
declare module 'wicg-focus-ring/test/specs/tabindex-one.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/tabindex-one'>;
}
declare module 'wicg-focus-ring/test/specs/tabindex-zero.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/tabindex-zero'>;
}
declare module 'wicg-focus-ring/test/specs/textarea.js' {
  declare module.exports: $Exports<'wicg-focus-ring/test/specs/textarea'>;
}
